### ISSUE TITLE
deleted navmesh

### ISSUE THREAD

**Issue by Jesseman1** [keilladraconis/Fallout-Vore#19]
Not sure if this has been addressed yet, but on the current release(3.1.1), wyrebash notifies that this mod contains a deleted navmesh that causes a CTD when referenced. I have crashed several times although they are usually rare. I'm hoping a new release can come out soon that solves this issue.

**Comment by keilladraconis** [comment]
Thank you! I didn't know about this and will clean it up ASAP. 

The next version will be 4.0 and will break compatibility with the old mod. Sorry I have had to gut a lot of stuff to resolve bugs and clean away cobwebs.

**Comment by keilladraconis** [comment]
The new requirements are updated, and I haven't tested furry/vulpine mods yet but I do use them. Spent a ton of time working on the new thicc slider system.

**Comment by keilladraconis** [comment]
I think this should be fixed in the 4.0.0 alpha: https://github.com/keilladraconis/Fallout-Vore/releases/tag/v4.0.0-alpha
