### ISSUE TITLE
V3.1.1 bugs

### ISSUE THREAD

**Issue by Jesseman1** [keilladraconis/Fallout-Vore#22]
With V4 coming out soon, I figure most if not all of these bugs are already fixed, but I thought I'd list the ones I came across just in case they were missed.

1: Being able to eat more than capacity should allow. If you are not completely full, you can still eat dead enemies even if you shouldn't be able to. For example: if you have a max capacity of 3 and are filled up to 2 or less, you could still eat a dead deathclaw. This only works when the enemy you are trying to eat is dead.

2: The inventory of digested enemies is not deleted, it gets dropped inside the FVStomachCell. I make it a point to periodically teleport to the stomach cell to clear out the dropped items there. If an important NPC or enemy gets stuck in the stomach cell, teleporting there to retrieve/kill them can cause massive lag if too many items have accumulated there. In addition, this has lead to a strange infinite duplicating weapons glitch within the stomach cell once before that could not be removed even with console commands.

3: Being able to eat gouls without the first level of Glowing Grub, and being able to eat robots like protectrons without the first level of Iron Rich Diet. Eating power armor does require the second level of Iron Rich Diet, but I cannot remember if the second level of Glowing Grub was required to eat super mutants.

4: Apex Predator, not sure what this perk is supposed to do, I've been able to eat pretty much anything, deathclaws and mirelurk queens included, without it.

5: Being able to swallow enemies that successfully block swallow attacks without getting the second or even first level of Mighty Blows.

6: Fast Metabolism does not passively heal while digesting prey(health bar going down), only granting health after digestion is finished(health bar hits 0).

7: Being able to move at full speed in combat while encumbered by prey without any levels of Rapacious Hunter.

8: Prey encumberment does not always take effect immediately, sometimes it doesn't take effect until after the prey is digested(health bar hits 0). The belly models seem to be tied to this, if there are already digested prey in your belly, and you swallow another, they belly will sometimes not appear(and additional encumberment will not apply) until after all prey are digested.

9: Sexual Tyrannosaurus, this perk description seems vague to me so I'm not sure what the intention is, but the last time I put full points into this(along with Beast Mode and Acid Strength) digestion was almost instantaneous and bellies would shrink down to nothing within seconds. This actually led to suffering from indigestion almost constantly.

I hope this list of bugs helps, this mod is extremely fun to play and I look forward to seeing it develop!

**Comment by keilladraconis** [comment]
I'm working on this once a week in my spare time so I don't have a lot of capacity to maintain multiple head versions with bugfixes.

Also it's a complicated mod with a long history, so actually working out the cause and resolution to many legacy features with complex and buggy implementations is time consuming, you know? 

So I'm doing what is most interesting to me presently, which is rewriting the mod systems, streamlining things, and eliminating excess complexity. Sorry but for now I have no plans to further fix 3.x version.

**Comment by Jesseman1** [comment]
Oh I wasn't expecting you to maintain multiple versions at once. I'm sorry if it came off that way. I can totally understand the time it takes to work on this. 

My intention with posting this bug list was to ask if all the new systems you're making for V4 solve these bugs. I suppose a better way to ask would be: do you think these bugs will still exist in V4, or do the new systems remove those problems?
